---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: content/about.md
  label: About
  match: "**/*"
- type: directory
  path: content/post
  label: Posts
  create: all
  match: "*"
  templates:
  - post
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.48'
